### ISSUE TITLE
OOM在三星的noteII上挺多的

### ISSUE THREAD

**Issue by wangdd1201** [xuehuayous/Android-LoopView#1]
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:627)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:603)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:407)
	at com.kevin.loopview.internal.loopimage.LoopImageCache.getBitmapFromDisk(LoopImageCache.java:146)
	at com.kevin.loopview.internal.loopimage.LoopImageCache.get(LoopImageCache.java:55)
	at com.kevin.loopview.internal.loopimage.LoopImage.getBitmap(LoopImage.java:44)
	at com.kevin.loopview.internal.loopimage.LoopImageTask.run(LoopImageTask.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by xuehuayous** [comment]
在1.1.0版本中移除了内部的图片加载引擎，可以通过设置任何图片加载引擎。
```
mBannerView.setImageLoader(new ImageLoader() {
    @Override
    public void loadImage(ImageView imageView, String url, int placeholder) {
        Glide.with(imageView.getContext()).load(url).into(imageView);
    }
});
```
